#!/bin/bash

read -p "Enter the file name: " file_name

read -p "Enter your input: " user_input

echo -e '#!/bin/bash\n'"$user_input" > "$file_name"

chmod +x "$file_name"

echo "Script file '$file_name' created successfully."

git add .
read -p "write the commit: " commit_message
git commit -m "$commit_message"
git push
echo ITS DONE YA BROOOOO
